version: "3"

services:
  db:
    image: mysql:8.0.31
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: edf6
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql

  app:
    image: ghcr.io/ty-v1/edf6-weapons/app:v1.0.0
    depends_on:
      - db
    command: [ "./wait-for-it.sh", "db:3306", "--", "node", "./dist/src/main.js" ]
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASSWORD}@db:3306/edf6?connect_timeout=3000"


volumes:
  mysql:
