version: "3"

services:

  app:
    image: ghcr.io/ty-v1/edf6-weapons/app:v2.0.0
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:/db/edf6.db"
    volumes:
      - ./db:/db
    command: node ./dist/src/main.js

  sqliteweb:
    image: ghcr.io/ty-v1/sqliteweb/sqliteweb:latest
    ports:
      - "8080:8080"
    volumes:
      - ./db:/db
    command: edf6.db
