version: "3"

services:
  db:
    image: mysql:8.0.31
    ports:
      - "13306:3306"

    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
